#include <iostream>
#include <string>

const static std::string test_log = std::string{ 
		"<source>: In function 'int main()':\n"
		"<source>:9:15: error: no match for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'test')"
		"    9 |     std::cout << test{};"
		"      |     ~~~~~~~~~ ^~ ~~~~~~"
		"      |          |       |"
		"      |          |       test"
		"      |          std::ostream {aka std::basic_ostream<char>}"
		"In file included from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/iostream:39,"
		"                 from <source>:1:"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:108:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(__ostream_type& (*)(__ostream_type&)) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  108 |       operator<<(__ostream_type& (*__pf)(__ostream_type&))"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:108:36: note:   no known conversion for argument 1 from 'test' to 'std::basic_ostream<char>::__ostream_type& (*)(std::basic_ostream<char>::__ostream_type&)' {aka 'std::basic_ostream<char>& (*)(std::basic_ostream<char>&)'}"
		"  108 |       operator<<(__ostream_type& (*__pf)(__ostream_type&))"
		"      |                  ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:117:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(__ios_type& (*)(__ios_type&)) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>; __ios_type = std::basic_ios<char>]'"
		"  117 |       operator<<(__ios_type& (*__pf)(__ios_type&))"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:117:32: note:   no known conversion for argument 1 from 'test' to 'std::basic_ostream<char>::__ios_type& (*)(std::basic_ostream<char>::__ios_type&)' {aka 'std::basic_ios<char>& (*)(std::basic_ios<char>&)'}"
		"  117 |       operator<<(__ios_type& (*__pf)(__ios_type&))"
		"      |                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:127:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::ios_base& (*)(std::ios_base&)) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  127 |       operator<<(ios_base& (*__pf) (ios_base&))"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:127:30: note:   no known conversion for argument 1 from 'test' to 'std::ios_base& (*)(std::ios_base&)'"
		"  127 |       operator<<(ios_base& (*__pf) (ios_base&))"
		"      |                  ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:166:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long int) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  166 |       operator<<(long __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:166:23: note:   no known conversion for argument 1 from 'test' to 'long int'"
		"  166 |       operator<<(long __n)"
		"      |                  ~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:170:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  170 |       operator<<(unsigned long __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:170:32: note:   no known conversion for argument 1 from 'test' to 'long unsigned int'"
		"  170 |       operator<<(unsigned long __n)"
		"      |                  ~~~~~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:174:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(bool) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  174 |       operator<<(bool __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:174:23: note:   no known conversion for argument 1 from 'test' to 'bool'"
		"  174 |       operator<<(bool __n)"
		"      |                  ~~~~~^~~"
		"In file included from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:833:"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:91:5: note: candidate: 'std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short int) [with _CharT = char; _Traits = std::char_traits<char>]'"
		"   91 |     basic_ostream<_CharT, _Traits>::"
		"      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:92:22: note:   no known conversion for argument 1 from 'test' to 'short int'"
		"   92 |     operator<<(short __n)"
		"      |                ~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:181:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(short unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  181 |       operator<<(unsigned short __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:181:33: note:   no known conversion for argument 1 from 'test' to 'short unsigned int'"
		"  181 |       operator<<(unsigned short __n)"
		"      |                  ~~~~~~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:105:5: note: candidate: 'std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(int) [with _CharT = char; _Traits = std::char_traits<char>]'"
		"  105 |     basic_ostream<_CharT, _Traits>::"
		"      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:106:20: note:   no known conversion for argument 1 from 'test' to 'int'"
		"  106 |     operator<<(int __n)"
		"      |                ~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:192:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  192 |       operator<<(unsigned int __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:192:31: note:   no known conversion for argument 1 from 'test' to 'unsigned int'"
		"  192 |       operator<<(unsigned int __n)"
		"      |                  ~~~~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:201:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long long int) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  201 |       operator<<(long long __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:201:28: note:   no known conversion for argument 1 from 'test' to 'long long int'"
		"  201 |       operator<<(long long __n)"
		"      |                  ~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:205:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long long unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  205 |       operator<<(unsigned long long __n)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:205:37: note:   no known conversion for argument 1 from 'test' to 'long long unsigned int'"
		"  205 |       operator<<(unsigned long long __n)"
		"      |                  ~~~~~~~~~~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:220:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(double) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  220 |       operator<<(double __f)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:220:25: note:   no known conversion for argument 1 from 'test' to 'double'"
		"  220 |       operator<<(double __f)"
		"      |                  ~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:224:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(float) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  224 |       operator<<(float __f)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:224:24: note:   no known conversion for argument 1 from 'test' to 'float'"
		"  224 |       operator<<(float __f)"
		"      |                  ~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:232:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long double) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  232 |       operator<<(long double __f)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:232:30: note:   no known conversion for argument 1 from 'test' to 'long double'"
		"  232 |       operator<<(long double __f)"
		"      |                  ~~~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:245:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(const void*) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>]'"
		"  245 |       operator<<(const void* __p)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:245:30: note:   no known conversion for argument 1 from 'test' to 'const void*'"
		"  245 |       operator<<(const void* __p)"
		"      |                  ~~~~~~~~~~~~^~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:250:7: note: candidate: 'std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::nullptr_t) [with _CharT = char; _Traits = std::char_traits<char>; __ostream_type = std::basic_ostream<char>; std::nullptr_t = std::nullptr_t]'"
		"  250 |       operator<<(nullptr_t)"
		"      |       ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:250:18: note:   no known conversion for argument 1 from 'test' to 'std::nullptr_t'"
		"  250 |       operator<<(nullptr_t)"
		"      |                  ^~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:119:5: note: candidate: 'std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(__streambuf_type*) [with _CharT = char; _Traits = std::char_traits<char>; __streambuf_type = std::basic_streambuf<char>]'"
		"  119 |     basic_ostream<_CharT, _Traits>::"
		"      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:120:34: note:   no known conversion for argument 1 from 'test' to 'std::basic_ostream<char>::__streambuf_type*' {aka 'std::basic_streambuf<char>*'}"
		"  120 |     operator<<(__streambuf_type* __sbin)"
		"      |                ~~~~~~~~~~~~~~~~~~^~~~~~"
		"In file included from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/basic_string.h:48,"
		"                 from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/string:53,"
		"                 from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/locale_classes.h:40,"
		"                 from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ios_base.h:41,"
		"                 from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ios:42,"
		"                 from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:38:"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/string_view:672:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, basic_string_view<_CharT, _Traits>)'"
		"  672 |     operator<<(basic_ostream<_CharT, _Traits>& __os,"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/string_view:672:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   'test' is not derived from 'std::basic_string_view<_CharT, _Traits>'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/basic_string.h:3883:5: note: candidate: 'template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, const __cxx11::basic_string<_CharT, _Traits, _Allocator>&)'"
		" 3883 |     operator<<(basic_ostream<_CharT, _Traits>& __os,"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/basic_string.h:3883:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   'test' is not derived from 'const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"In file included from /opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ios_base.h:46:"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/system_error:279:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, const error_code&)'"
		"  279 |     operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/system_error:279:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const std::error_code&'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:507:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, _CharT)'"
		"  507 |     operator<<(basic_ostream<_CharT, _Traits>& __out, _CharT __c)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:507:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   deduced conflicting types for parameter '_CharT' ('char' and 'test')"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:517:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, char)'"
		"  517 |     operator<<(basic_ostream<_CharT, _Traits>& __out, char __c)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:517:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'char'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:523:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char)'"
		"  523 |     operator<<(basic_ostream<char, _Traits>& __out, char __c)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:523:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'char'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:534:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, signed char)'"
		"  534 |     operator<<(basic_ostream<char, _Traits>& __out, signed char __c)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:534:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'signed char'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:539:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, unsigned char)'"
		"  539 |     operator<<(basic_ostream<char, _Traits>& __out, unsigned char __c)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:539:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'unsigned char'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:548:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, wchar_t)' (deleted)"
		"  548 |     operator<<(basic_ostream<char, _Traits>&, wchar_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:548:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'wchar_t'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:553:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char8_t)' (deleted)"
		"  553 |     operator<<(basic_ostream<char, _Traits>&, char8_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:553:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'char8_t'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:558:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char16_t)' (deleted)"
		"  558 |     operator<<(basic_ostream<char, _Traits>&, char16_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:558:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'char16_t'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:562:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char32_t)' (deleted)"
		"  562 |     operator<<(basic_ostream<char, _Traits>&, char32_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:562:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'char32_t'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:568:5: note: candidate: 'template<class _Traits> std::basic_ostream<wchar_t, _Traits>& std::operator<<(basic_ostream<wchar_t, _Traits>&, char8_t)' (deleted)"
		"  568 |     operator<<(basic_ostream<wchar_t, _Traits>&, char8_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:568:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'wchar_t' and 'char'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:573:5: note: candidate: 'template<class _Traits> std::basic_ostream<wchar_t, _Traits>& std::operator<<(basic_ostream<wchar_t, _Traits>&, char16_t)' (deleted)"
		"  573 |     operator<<(basic_ostream<wchar_t, _Traits>&, char16_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:573:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'wchar_t' and 'char'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:577:5: note: candidate: 'template<class _Traits> std::basic_ostream<wchar_t, _Traits>& std::operator<<(basic_ostream<wchar_t, _Traits>&, char32_t)' (deleted)"
		"  577 |     operator<<(basic_ostream<wchar_t, _Traits>&, char32_t) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:577:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'wchar_t' and 'char'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:598:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, const _CharT*)'"
		"  598 |     operator<<(basic_ostream<_CharT, _Traits>& __out, const _CharT* __s)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:598:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'const _CharT*' and 'test'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:302:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(basic_ostream<_CharT, _Traits>&, const char*)'"
		"  302 |     operator<<(basic_ostream<_CharT, _Traits>& __out, const char* __s)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/bits/ostream.tcc:302:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const char*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:615:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const char*)'"
		"  615 |     operator<<(basic_ostream<char, _Traits>& __out, const char* __s)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:615:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const char*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:628:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const signed char*)'"
		"  628 |     operator<<(basic_ostream<char, _Traits>& __out, const signed char* __s)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:628:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const signed char*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:633:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const unsigned char*)'"
		"  633 |     operator<<(basic_ostream<char, _Traits>& __out, const unsigned char* __s)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:633:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const unsigned char*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:642:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const wchar_t*)' (deleted)"
		"  642 |     operator<<(basic_ostream<char, _Traits>&, const wchar_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:642:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const wchar_t*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:647:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const char8_t*)' (deleted)"
		"  647 |     operator<<(basic_ostream<char, _Traits>&, const char8_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:647:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const char8_t*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:652:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const char16_t*)' (deleted)"
		"  652 |     operator<<(basic_ostream<char, _Traits>&, const char16_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:652:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const char16_t*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:656:5: note: candidate: 'template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, const char32_t*)' (deleted)"
		"  656 |     operator<<(basic_ostream<char, _Traits>&, const char32_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:656:5: note:   template argument deduction/substitution failed:"
		"<source>:9:18: note:   cannot convert 'test()' (type 'test') to type 'const char32_t*'"
		"    9 |     std::cout << test{};"
		"      |                  ^~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:662:5: note: candidate: 'template<class _Traits> std::basic_ostream<wchar_t, _Traits>& std::operator<<(basic_ostream<wchar_t, _Traits>&, const char8_t*)' (deleted)"
		"  662 |     operator<<(basic_ostream<wchar_t, _Traits>&, const char8_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:662:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'wchar_t' and 'char'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:667:5: note: candidate: 'template<class _Traits> std::basic_ostream<wchar_t, _Traits>& std::operator<<(basic_ostream<wchar_t, _Traits>&, const char16_t*)' (deleted)"
		"  667 |     operator<<(basic_ostream<wchar_t, _Traits>&, const char16_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:667:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'wchar_t' and 'char'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:671:5: note: candidate: 'template<class _Traits> std::basic_ostream<wchar_t, _Traits>& std::operator<<(basic_ostream<wchar_t, _Traits>&, const char32_t*)' (deleted)"
		"  671 |     operator<<(basic_ostream<wchar_t, _Traits>&, const char32_t*) = delete;"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:671:5: note:   template argument deduction/substitution failed:"
		"<source>:9:23: note:   mismatched types 'wchar_t' and 'char'"
		"    9 |     std::cout << test{};"
		"      |                       ^"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:754:5: note: candidate: 'template<class _Ostream, class _Tp> _Ostream&& std::operator<<(_Ostream&&, const _Tp&)'"
		"  754 |     operator<<(_Ostream&& __os, const _Tp& __x)"
		"      |     ^~~~~~~~"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:754:5: note:   template argument deduction/substitution failed:"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream: In substitution of 'template<class _Ostream, class _Tp> _Ostream&& std::operator<<(_Ostream&&, const _Tp&) [with _Ostream = std::basic_ostream<char>&; _Tp = test]':"
		"<source>:9:23:   required from here"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:754:5: error: template constraint failure for 'template<class _Os, class _Tp>  requires (__derived_from_ios_base<_Os>) && requires(_Os& __os, const _Tp& __t) {__os << __t;} using __rvalue_stream_insertion_t = _Os&&'"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:754:5: note: constraints not satisfied"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream: In substitution of 'template<class _Os, class _Tp>  requires (__derived_from_ios_base<_Os>) && requires(_Os& __os, const _Tp& __t) {__os << __t;} using __rvalue_stream_insertion_t = _Os&& [with _Os = std::basic_ostream<char>&; _Tp = test]':"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:754:5:   required by substitution of 'template<class _Ostream, class _Tp> _Ostream&& std::operator<<(_Ostream&&, const _Tp&) [with _Ostream = std::basic_ostream<char>&; _Tp = test]'"
		"<source>:9:23:   required from here"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:721:13:   required for the satisfaction of '__derived_from_ios_base<_Os>' [with _Os = std::basic_ostream<char, std::char_traits<char> >&]"
		"/opt/compiler-explorer/gcc-12.1.0/include/c++/12.1.0/ostream:721:39: note: the expression 'is_class_v<_Tp> [with _Tp = std::basic_ostream<char, std::char_traits<char> >&]' evaluated to 'false'"
		"  721 |     concept __derived_from_ios_base = is_class_v<_Tp>"
		"      |                                       ^~~~~~~~~~~~~~~"
	};

